language: php

dist: precise

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - composer require friendsofphp/php-cs-fixer
  - composer install --no-progress --no-ansi --no-interaction --profile

script:
  - composer csfixer

notifications:
  email: false
# vim:fdl=0:sts=2:sw=2:ts=2
